apiVersion: v1
kind: ConfigMap
metadata:
  name: rmq-rabbitmq-extra
  namespace: {{ .Release.Namespace }}
  labels:
    app: {{ template "rabbitmq-ha.name" . }}
    chart: {{ template "rabbitmq-ha.chart" . }}
    release: {{ .Release.Name }}
    heritage: {{ .Release.Service }}
binaryData:
  rabbitmq_delayed_message_exchange-3.8.9-0199d11c.ez: {{ .Files.Get "files/rabbitmq_delayed_message_exchange-3.8.9-0199d11c.ez" | b64enc }}